### ISSUE TITLE
setenv command not working

### ISSUE THREAD

**Issue by jyjd99** [andrewjahn/FreeSurfer_Scripts#1]
Dear Andy

Thank you for your fantastic tutorial for all different kinds of neuroimaging analysis programs. 
Currently, I am learning how to use FreeSurfer and followed your tutorials.
I faced some problems to use your scripts. 

1. My macOS is bigsur versos 11.4. 
2. I use the shell (/bin/tcsh) you are using in the tutorial. 

Somehow 'setenv' command is not working. I wonder whether you have solution for this or whether you know where to look up .

I am looking forward to hearing from you. Thank you.

**Comment by andrewjahn** [comment]
Hi there,

Apologies for the late reply; I was going through old issues, and I must have missed this one. Are you still having this issue, and if so, what error is it giving you?


Best,

-Andy
